# Generated by Django 2.2.24 on 2021-06-09 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ENTInstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uai",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        verbose_name="Unité Administrative Immatriculée",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'institution"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        null=True, verbose_name="Date de fin d'abonnement"
                    ),
                ),
                (
                    "ent",
                    models.CharField(
                        choices=[
                            ("ESIDOC", "Esidoc"),
                            ("HDF", "Hauts-de-France"),
                            ("OCCITANIE", "Occitanie"),
                            ("OCCITANIEAGR", "Occitanie lycée agricole"),
                            ("CORRELYCE", "Corrélyce"),
                            ("GMINVENT", "GMInvent"),
                            ("C3RB", "C3rb"),
                        ],
                        default="HDF",
                        max_length=12,
                        verbose_name="Environnements Numériques de Travail",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
