# Generated by Django 2.2.24 on 2021-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ent", "0002_auto_20210610_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entinstitution",
            name="ent",
            field=models.CharField(
                choices=[
                    ("HDF", "Hauts-de-France"),
                    ("OCCITANIE", "Occitanie"),
                    ("OCCITANIEAGR", "Occitanie lycée agricole"),
                    ("CORRELYCE", "Corrélyce"),
                    ("GMINVENT", "GMInvent"),
                ],
                default="HDF",
                max_length=12,
                verbose_name="Environnements Numériques de Travail",
            ),
        ),
    ]
